# TODO: The application is trying to bind to port 8080, which is restricted in this environment.
# Change the server port to 8081.

server.port=8080

# Expose actuator endpoints
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
